### PR TITLE
build(application) create application architecture

### PR DESCRIPTION
**Pull request by fabiankoziolek**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/igroup-opole/yesterday-api/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```
Created application architecture

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

### CODE REVIEW

**Comment by AlexTorianyk** [comment]
Very nice pull request by the king of pull requestsm I approve.

**Comment by fabiankoziolek** [comment]
[[backend] Design architecutre of the application](https://trello.com/c/AMDdjowx/68-backend-design-architecutre-of-the-application)

**Comment by rafalschmidt97** [comment]
screenshot 2018-11-30 at 18 31 01

Travis passed but there are 3 warnings to solve.

**Comment by rafalschmidt97** [comment]
@fabiankoziolek, @AlexTorianyk - entities should have required fields. Also I dont know why you've created all classes when we do TDD...

**Pull request merged**
